"""
build_topics.py
----------------
Generates data/topics.json for SpeakForge.

This is the ONLY place topic content is authored in Python form; the app
itself never imports this file — it only reads the generated JSON.
To add content: edit CATEGORIES / TOPICS below and re-run:
    python3 scripts/build_topics.py
"""
import json
import re
import os

def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")

def T(title, diff, mins, intro, concepts, points, questions, apps, vocab, keywords):
    return dict(title=title, difficulty=diff, estSpeakingTime=mins, intro=intro,
                concepts=concepts, discussionPoints=points, questions=questions,
                applications=apps, vocabulary=vocab, keywords=keywords)

CATEGORIES = [
    dict(id="ai", name="Artificial Intelligence", color="blue", icon="cpu"),
    dict(id="ml", name="Machine Learning", color="blue", icon="brain"),
    dict(id="datascience", name="Data Science", color="blue", icon="chart"),
    dict(id="finance", name="Finance", color="gold", icon="landmark"),
    dict(id="investing", name="Investing", color="gold", icon="trending-up"),
    dict(id="economics", name="Economics", color="gold", icon="globe"),
    dict(id="entrepreneurship", name="Entrepreneurship", color="emerald", icon="rocket"),
    dict(id="strategy", name="Business Strategy", color="emerald", icon="chess"),
    dict(id="leadership", name="Leadership", color="emerald", icon="compass"),
    dict(id="negotiation", name="Negotiation", color="emerald", icon="handshake"),
    dict(id="decisionmaking", name="Decision Making", color="purple", icon="split"),
    dict(id="philosophy", name="Philosophy", color="purple", icon="feather"),
    dict(id="psychology", name="Human Behaviour", color="purple", icon="mind"),
    dict(id="mathematics", name="Mathematics", color="navy", icon="sigma"),
    dict(id="technology", name="Technology", color="navy", icon="chip"),
    dict(id="blockchain", name="Blockchain", color="navy", icon="link"),
    dict(id="cybersecurity", name="Cybersecurity", color="navy", icon="shield"),
    dict(id="space", name="Space", color="navy", icon="orbit"),
    dict(id="climate", name="Climate Change", color="emerald", icon="leaf"),
    dict(id="communication", name="Communication", color="purple", icon="mic"),
]

TOPICS = {
"ai": [
 T("Transformer Architecture","Advanced",3,
   "The neural network design behind almost every modern language model.",
   ["Self-attention vs recurrence","Positional encoding","Encoder-decoder vs decoder-only","Parallelisation over sequences"],
   ["Why did transformers replace RNNs so fast?","Is bigger context always better?","What breaks at very long sequences?"],
   ["Would a non-attention architecture ever make a comeback, and why?","Is scaling transformers alone enough to reach general intelligence?"],
   ["Machine translation","Code generation","Protein folding (AlphaFold)"],
   [dict(word="parallelisable",definition="can be split and run at once"),dict(word="quadratic cost",definition="cost that grows very fast with size")],
   ["attention","tokens","context window","self-attention","positional encoding"]),
 T("Attention Mechanism","Intermediate",2,
   "The technique that lets a model decide which words matter most to each other.",
   ["Query, key, value vectors","Softmax weighting","Multi-head attention","Interpretability of attention maps"],
   ["Does attention equal explanation?","Why multiple heads instead of one?","How does attention scale with sequence length?"],
   ["Can attention weights be trusted as a model's 'reasoning'?","Would a human benefit from thinking in 'attention weights'?"],
   ["Search ranking","Summarisation","Speech recognition"],
   [dict(word="weighting",definition="giving more importance to")],
   ["query","key","value","softmax","multi-head"]),
 T("Retrieval-Augmented Generation (RAG)","Intermediate",2,
   "Combining a language model with an external knowledge source at answer time.",
   ["Vector search","Chunking documents","Grounding vs hallucination","Freshness of knowledge"],
   ["Why not just fine-tune instead of retrieving?","What happens if retrieval returns the wrong chunk?","How do you evaluate a RAG system?"],
   ["Is RAG a permanent fix for hallucination or a patch?","Should every AI product use RAG by default?"],
   ["Customer support bots","Legal research tools","Internal company search"],
   [dict(word="grounding",definition="basing an answer on real evidence")],
   ["retrieval","embeddings","vector database","chunking","hallucination"]),
 T("AI Alignment","Advanced",3,
   "The problem of making AI systems pursue the goals we actually intend.",
   ["Reward hacking","Value specification","Interpretability","Scalable oversight"],
   ["Why is specifying 'good behaviour' so hard?","Is alignment a technical or a social problem?","What does 'aligned' even mean across cultures?"],
   ["Can a system ever be proven aligned, or only tested?","Who should decide what values a powerful AI optimises for?"],
   ["RLHF-tuned chatbots","Autonomous trading agents","Self-driving decision systems"],
   [dict(word="reward hacking",definition="gaming the score instead of the goal")],
   ["alignment","reward function","oversight","specification gaming"]),
 T("Agentic AI","Intermediate",2,
   "Systems that plan, use tools, and take multi-step actions toward a goal.",
   ["Planning loops","Tool use","Memory across steps","Failure recovery"],
   ["What stops an agent from looping forever?","How much autonomy is safe to grant?","Should agents ask for permission before acting?"],
   ["Will most software become agentic within a decade?","What's the right amount of human-in-the-loop for agents?"],
   ["Coding assistants","Research agents","Autonomous customer service"],
   [dict(word="autonomy",definition="ability to act without supervision")],
   ["agent","tool use","planning","memory","autonomy"]),
 T("LangGraph & Orchestration","Intermediate",2,
   "Frameworks for wiring multiple AI calls and tools into a controllable workflow.",
   ["State machines for agents","Branching and retries","Human-in-the-loop checkpoints","Observability"],
   ["Why do agent workflows need explicit state?","When is a simple chain enough vs needing a graph?","How do you debug a multi-step agent?"],
   ["Is orchestration tooling solving a temporary gap or a lasting need?"],
   ["Multi-step research assistants","Automated report generation","Financial data pipelines"],
   [dict(word="orchestration",definition="coordinating many parts to work together")],
   ["state graph","node","checkpoint","observability"]),
 T("Model Quantization","Advanced",3,
   "Shrinking a model's numerical precision to make it faster and cheaper to run.",
   ["FP16 vs INT8 vs INT4","Accuracy vs speed trade-off","Hardware efficiency","Post-training vs quantization-aware training"],
   ["How much accuracy is acceptable to lose for speed?","Why does quantization matter for edge devices?"],
   ["Will future chips make quantization unnecessary?"],
   ["Running LLMs on phones","Cheaper inference at scale","Edge robotics"],
   [dict(word="precision",definition="how exact the numbers are")],
   ["quantization","inference","precision","edge device"]),
 T("LLM Hallucination","Intermediate",2,
   "When a model states something false with full confidence.",
   ["Why hallucination happens statistically","Confidence vs correctness","Mitigations: grounding, citations, verification"],
   ["Can hallucination ever be fully eliminated?","Should models say 'I don't know' more often?"],
   ["Is hallucination a bug or an inherent trait of generative models?"],
   ["Legal drafting risk","Medical advice risk","Customer-facing chatbots"],
   [dict(word="confidence",definition="how sure something sounds")],
   ["hallucination","grounding","confidence","factuality"]),
],
"ml": [
 T("Gradient Descent","Intermediate",2,
   "The optimisation method that nudges a model's parameters toward lower error.",
   ["Learning rate","Local minima vs saddle points","Batch vs stochastic updates","Momentum"],
   ["Why not just solve for the minimum directly?","What happens if the learning rate is too high?"],
   ["Is gradient descent the reason deep learning works, or just good enough?"],
   ["Training neural networks","Fitting regression models"],
   [dict(word="optimisation",definition="finding the best possible value")],
   ["gradient","learning rate","loss function","convergence"]),
 T("Overfitting & Regularisation","Beginner",2,
   "When a model memorises training data instead of learning general patterns.",
   ["Train vs test error gap","Dropout","L1/L2 penalties","Early stopping"],
   ["How do you know a model is overfitting?","Why does more data usually help?"],
   ["Is overfitting purely a technical problem, or also a data problem?"],
   ["Medical diagnosis models","Credit scoring models"],
   [dict(word="generalise",definition="perform well on new, unseen data")],
   ["overfitting","regularisation","dropout","generalisation"]),
 T("Bias-Variance Tradeoff","Intermediate",2,
   "The balance between a model being too simple or too sensitive to noise.",
   ["High bias = underfitting","High variance = overfitting","Ensemble methods reducing variance"],
   ["Can you reduce both bias and variance at once?","How does model complexity map to this tradeoff?"],
   ["Does this tradeoff still apply to today's massive models?"],
   ["Model selection in production systems"],
   [dict(word="variance",definition="how much predictions swing with new data")],
   ["bias","variance","underfitting","ensemble"]),
 T("Random Forests & Ensembles","Beginner",2,
   "Combining many weak models to make one strong prediction.",
   ["Bagging vs boosting","Decision tree basics","Voting/averaging predictions"],
   ["Why do many weak models beat one strong model?","When would you avoid ensembles?"],
   ["Is model simplicity undervalued in an era obsessed with deep learning?"],
   ["Fraud detection","Credit risk models"],
   [dict(word="ensemble",definition="a group working together")],
   ["bagging","boosting","decision tree","ensemble"]),
 T("Reinforcement Learning from Human Feedback (RLHF)","Advanced",3,
   "Training a model using human preference rankings rather than fixed labels.",
   ["Reward model training","Policy optimisation","Preference data collection","Reward hacking risk"],
   ["Why not just use supervised learning alone?","How representative are the humans providing feedback?"],
   ["Whose preferences should shape a widely-used AI's behaviour?"],
   ["Chatbot tone tuning","Recommendation systems"],
   [dict(word="reward model",definition="a model trained to score good responses")],
   ["reward model","policy","preference data","fine-tuning"]),
 T("Feature Engineering","Beginner",2,
   "Shaping raw data into inputs a model can actually learn from.",
   ["Encoding categorical data","Scaling numerical data","Domain-driven features"],
   ["Why does feature quality often matter more than model choice?","Is feature engineering dying with deep learning?"],
   ["Will automated feature learning fully replace manual feature engineering?"],
   ["Tabular data in finance","Sensor data in manufacturing"],
   [dict(word="encoding",definition="converting data into a usable numeric form")],
   ["feature","encoding","scaling","domain knowledge"]),
 T("Model Evaluation Metrics","Beginner",2,
   "The numbers used to judge whether a model is actually good.",
   ["Precision vs recall","ROC-AUC","F1 score","Choosing the right metric for the problem"],
   ["Why can a model have 99% accuracy and still be useless?","When does recall matter more than precision?"],
   ["Should a single metric ever fully decide if a model ships?"],
   ["Spam detection","Cancer screening models"],
   [dict(word="precision",definition="how many flagged cases were actually correct")],
   ["precision","recall","F1 score","confusion matrix"]),
 T("Transfer Learning","Intermediate",2,
   "Reusing a model trained on one task as the starting point for another.",
   ["Pretraining vs fine-tuning","Frozen vs trainable layers","Domain shift"],
   ["Why start from a pretrained model instead of from scratch?","When does transfer learning fail?"],
   ["Is transfer learning making from-scratch training obsolete?"],
   ["Medical imaging with limited data","Fine-tuning LLMs for a company's domain"],
   [dict(word="fine-tuning",definition="further training on a specific task")],
   ["pretraining","fine-tuning","domain shift","frozen layers"]),
],
"finance": [
 T("Time Value of Money","Beginner",2,
   "The principle that a rupee today is worth more than a rupee tomorrow.",
   ["Present value vs future value","Discount rate","Compounding frequency"],
   ["Why does inflation alone justify this principle?","How does discount rate choice change a valuation?"],
   ["Is a low discount rate a sign of optimism or recklessness in a valuation?"],
   ["Bond pricing","Retirement planning","Project valuation"],
   [dict(word="discount rate",definition="the rate used to shrink future money to today's value")],
   ["present value","future value","discounting","compounding"]),
 T("Capital Structure","Intermediate",2,
   "How a company splits its funding between debt and equity.",
   ["Debt vs equity trade-off","Cost of capital","Financial leverage","Bankruptcy risk"],
   ["Why would a profitable company still take on debt?","How does leverage amplify both gains and losses?"],
   ["Is there really an 'optimal' capital structure, or is it always contextual?"],
   ["Startup fundraising decisions","Corporate buybacks"],
   [dict(word="leverage",definition="using borrowed money to increase potential return")],
   ["debt","equity","leverage","cost of capital"]),
 T("Derivatives: Options & Futures","Advanced",3,
   "Financial contracts whose value depends on an underlying asset.",
   ["Calls vs puts","Hedging vs speculation","Payoff diagrams","Margin requirements"],
   ["Why do derivatives get blamed for financial crises?","Is hedging just insurance, or is it also a bet?"],
   ["Should retail investors be allowed the same access to derivatives as institutions?"],
   ["Corporate currency hedging","Portfolio protection", "Commodity price locking"],
   [dict(word="hedging",definition="reducing risk by taking an offsetting position")],
   ["call option","put option","strike price","hedge"]),
 T("Financial Statement Analysis","Intermediate",3,
   "Reading a company's numbers to judge its real financial health.",
   ["Income statement vs balance sheet vs cash flow","Ratio analysis","Red flags in reported earnings"],
   ["Why can a profitable company still run out of cash?","What ratios matter most for a growth company vs a mature one?"],
   ["Can financial statements ever be fully trusted without independent checks?"],
   ["Equity research","Credit underwriting","M&A due diligence"],
   [dict(word="liquidity",definition="how easily assets convert to cash")],
   ["balance sheet","cash flow","liquidity","ratio analysis"]),
 T("Mergers & Acquisitions","Advanced",3,
   "How companies combine, and the financial logic behind the deals.",
   ["Synergies","Valuation methods (DCF, comps)","Deal financing","Integration risk"],
   ["Why do most M&A deals fail to create value?","How do you value 'synergy' before it exists?"],
   ["Is the pursuit of scale through M&A usually about strategy or ego?"],
   ["Cross-border acquisitions","Private equity buyouts"],
   [dict(word="synergy",definition="extra value from combining two things")],
   ["synergy","valuation","due diligence","integration"]),
 T("Risk Management in Banking","Advanced",3,
   "How financial institutions measure and control the risks they take on.",
   ["Credit risk vs market risk vs operational risk","Value at Risk (VaR)","Stress testing","Regulatory capital"],
   ["Why did risk models fail during the 2008 crisis?","How much risk-taking is healthy for an economy?"],
   ["Can risk ever truly be quantified, or only estimated?"],
   ["Bank capital requirements","Trading desk risk limits"],
   [dict(word="stress testing",definition="checking how a system holds up under extreme conditions")],
   ["value at risk","credit risk","stress test","capital adequacy"]),
 T("Behavioural Finance","Intermediate",2,
   "Why real investors don't behave like the rational actors in textbooks.",
   ["Loss aversion","Herd behaviour","Overconfidence bias","Anchoring"],
   ["Why do smart people still make irrational money decisions?","How do markets exploit predictable human biases?"],
   ["Can behavioural biases ever be fully 'trained out' of a professional investor?"],
   ["Retail trading apps","Retirement savings design"],
   [dict(word="loss aversion",definition="feeling losses more strongly than equal gains")],
   ["loss aversion","herd behaviour","anchoring","overconfidence"]),
 T("Central Bank Policy","Advanced",3,
   "How interest rate and money supply decisions ripple through an economy.",
   ["Interest rate policy","Quantitative easing","Inflation targeting","Independence of central banks"],
   ["Why does a small rate change move global markets?","Should central banks be fully independent from government?"],
   ["Is inflation targeting still the right framework for today's economy?"],
   ["Mortgage rates","Currency valuation","Corporate borrowing costs"],
   [dict(word="quantitative easing",definition="a central bank buying assets to add money to the economy")],
   ["interest rate","quantitative easing","inflation target","monetary policy"]),
],
"investing": [
 T("Value Investing","Intermediate",2,
   "Buying assets for meaningfully less than their intrinsic worth.",
   ["Intrinsic value vs price","Margin of safety","Contrarian positioning"],
   ["How do you estimate intrinsic value without perfect information?","Why does value investing go out of fashion for years at a time?"],
   ["Is value investing still viable in markets dominated by algorithms?"],
   ["Long-term equity portfolios","Distressed asset investing"],
   [dict(word="intrinsic value",definition="what something is really worth, beyond market price")],
   ["margin of safety","intrinsic value","contrarian","undervalued"]),
 T("Portfolio Diversification","Beginner",2,
   "Spreading investments to reduce the impact of any single loss.",
   ["Correlation between assets","Systematic vs idiosyncratic risk","Rebalancing"],
   ["Can you be 'too diversified'?","Why doesn't diversification protect against every crash?"],
   ["Is home-country bias in portfolios a mistake or a reasonable choice?"],
   ["Retirement funds","Index fund construction"],
   [dict(word="correlation",definition="how closely two things move together")],
   ["diversification","correlation","systematic risk","rebalancing"]),
 T("Efficient Market Hypothesis","Advanced",3,
   "The theory that asset prices already reflect all available information.",
   ["Weak vs semi-strong vs strong form","Implications for active management","Anomalies that challenge it"],
   ["If markets are efficient, why do bubbles happen?","Can any investor consistently beat the market?"],
   ["Is EMH a description of reality or a useful simplifying assumption?"],
   ["Index fund vs active fund debate","Insider trading regulation"],
   [dict(word="anomaly",definition="something that doesn't fit the expected pattern")],
   ["efficient market","active management","anomaly","alpha"]),
 T("Quantitative Trading Strategies","Advanced",3,
   "Using mathematical models and data to systematically trade markets.",
   ["Statistical arbitrage","Momentum vs mean reversion","Backtesting pitfalls","Execution and slippage"],
   ["Why do backtested strategies often fail live?","How much of quant success is skill vs market regime luck?"],
   ["Will markets eventually become too efficient for quant strategies to work?"],
   ["Hedge fund alpha generation","High-frequency trading"],
   [dict(word="backtesting",definition="testing a strategy on historical data")],
   ["statistical arbitrage","momentum","mean reversion","backtest"]),
 T("Asset Allocation","Intermediate",2,
   "Deciding how to split money across stocks, bonds, cash, and alternatives.",
   ["Risk tolerance vs time horizon","Strategic vs tactical allocation","Life-cycle investing"],
   ["Why does age typically shift allocation toward bonds?","How should allocation change during a crisis?"],
   ["Should retail investors attempt tactical allocation at all?"],
   ["Pension fund management","Robo-advisor design"],
   [dict(word="risk tolerance",definition="how much loss someone can accept")],
   ["allocation","risk tolerance","time horizon","rebalancing"]),
 T("Venture Capital Investing","Intermediate",2,
   "Funding early, high-risk companies in exchange for equity and outsized upside.",
   ["Power law returns","Term sheets","Follow-on investing","Exit strategy"],
   ["Why do VCs accept that most bets will fail?","How do you value a company with no revenue?"],
   ["Is the power-law model of VC returns sustainable long-term?"],
   ["Startup fundraising rounds","Corporate venture arms"],
   [dict(word="power law",definition="a pattern where a few outcomes drive most results")],
   ["term sheet","power law","valuation","exit"]),
 T("Cryptocurrency as an Asset Class","Intermediate",2,
   "Digital assets and the debate over whether they belong in a portfolio.",
   ["Volatility vs traditional assets","Store of value narrative","Regulatory uncertainty"],
   ["Is crypto a currency, a commodity, or a speculative asset?","How should risk-averse investors think about crypto exposure?"],
   ["Will regulation make crypto more like traditional finance, or undermine its purpose?"],
   ["Portfolio hedging debates","Cross-border payments"],
   [dict(word="volatility",definition="how sharply a price swings")],
   ["volatility","store of value","regulation","digital asset"]),
 T("Bond Markets & Yield Curves","Advanced",3,
   "How debt markets price risk and time, and what the yield curve signals.",
   ["Yield vs price relationship","Inverted yield curve as recession signal","Credit spreads"],
   ["Why does an inverted yield curve worry economists?","How do interest rate expectations shape the curve?"],
   ["Is the yield curve still a reliable recession predictor today?"],
   ["Government debt issuance","Corporate bond investing"],
   [dict(word="yield curve",definition="a chart of interest rates across different loan durations")],
   ["yield curve","credit spread","duration","inversion"]),
],
}

def build():
    topics = []
    for cat_id, items in TOPICS.items():
        for t in items:
            entry = dict(t)
            entry["id"] = f"{cat_id}-{slug(t['title'])}"
            entry["categoryId"] = cat_id
            topics.append(entry)

    covered = set(TOPICS.keys())
    extra_categories = [c for c in CATEGORIES if c["id"] not in covered]

    # Lightweight starter subtopics for remaining categories so every
    # category on the homepage is immediately usable. Marked "Starter"
    # so it's obvious these are meant to be expanded (see CUSTOMIZATION.md).
    for cat in extra_categories:
        base = cat["name"]
        for i, angle in enumerate([
            f"Core Principles of {base}",
            f"A Turning Point in {base}",
            f"A Controversial Debate in {base}",
            f"{base} in Everyday Life",
            f"The Future of {base}",
            f"A Common Misconception in {base}",
        ]):
            topics.append(dict(
                id=f"{cat['id']}-{slug(angle)}",
                categoryId=cat["id"],
                title=angle,
                difficulty=["Beginner","Intermediate","Advanced"][i % 3],
                estSpeakingTime=2,
                intro=f"A starter prompt on {base.lower()} — expand this entry with real detail in data/topics.json.",
                concepts=[f"Key idea #{n+1} in {base}" for n in range(3)],
                discussionPoints=[f"Discussion angle #{n+1}" for n in range(3)],
                questions=[f"What is the most important open question in {base.lower()} today?"],
                applications=[f"A real application of {base.lower()}"],
                vocabulary=[dict(word="starter entry", definition="placeholder content meant to be replaced")],
                keywords=[base.lower()],
            ))

    data = dict(categories=CATEGORIES, topics=topics)
    out_path = os.path.join(os.path.dirname(__file__), "..", "data", "topics.json")
    with open(out_path, "w") as f:
        json.dump(data, f, indent=2)
    print(f"Wrote {len(topics)} topics across {len(CATEGORIES)} categories -> {out_path}")

if __name__ == "__main__":
    build()
